before_script:
  - echo "$ENV_CONTENT" >> .env

variables:
  POSTGRES_DB: $DB_DATABASE
  POSTGRES_USER: $DB_USERNAME
  POSTGRES_PASSWORD: $DB_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT:
    $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  ENV_CONTENT: $prodenv
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # When I add this variable everything start working
  DOCKER_HOST: tcp://docker:2376

stages:
  - build
  - test
  - production

build:
  image: docker:latest
  stage: build
  #  cache:
  #    key: ${CI_COMMIT_REF_SLUG}-build
  #    paths:
  #      - vendor/
  services:
    - docker:24.0.5-dind
  script:
    - echo "$TAG_COMMIT"
    - echo "$TAG_LATEST"
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY"
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    # Not working wrong password or login
    #    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

pest-testing:
  image: lorisleiva/laravel-docker:8.2
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate
    - php artisan test

deploy:
  image: alpine:latest
  stage: production
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo '$CI_REGISTRY_PASSWORD' | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f laravel_cicd || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8080:80 --name laravel_cicd $TAG_COMMIT"
  environment:
    name: production
    url: http://16.170.250.26:8080
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
