version: "3.3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_cicd
        container_name: laravel_cicd
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        networks:
            - app-network

    postgres:
        image: postgres:16
        ports:
            - "5432"
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - db-data:/var/lib/psql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
        driver: local
