version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: cicd.Dockerfile
    image: laravel_cicd
    container_name: laravel_cicd
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
